### ISSUE TITLE
Multiplication

### ISSUE THREAD

**Issue by AlexReusC** [AlexReusC/acastro-project-demo#3]
mult...

**Comment by Daniel-dadu** [comment]
![hacker](https://user-images.githubusercontent.com/67434516/109236685-bb3b7300-7795-11eb-8076-5c69eeb6892f.jpg)

Llegó el hacker

**Comment by AlexReusC** [comment]
va we codificalo jaja

**Comment by AlexReusC** [comment]
rolalo

**Comment by Daniel-dadu** [comment]
nel :)
